
trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04'
  
container: mcr.microsoft.com/playwright:next

steps:

  - script: |
      export GRADLE_OPTS="-Xmx1024m -XX:MaxMetaspaceSize=256m"
      export GRADLE_USER_HOME=".gradle-home"
    displayName: 'Set environment variables'

  - script: |
      mkdir -p executor
      cd executor
      sudo apt-get update
      sudo apt-get install -y jq
      sudo apt-get install -y unzip
      node -v
      printf '{ "key": "%s"}' $MUUKTEST_KEY > file.json
      curl -H  "Content-Type: application/json" -X POST -d @file.json 'https://portal.muuktest.com:8081/generate_token_executer' -o "token.json"
      curl -X POST https://portal.muuktest.com:8081/api/v1/downloadpwfiles -k -d @file.json -H "Content-Type: application/json" -o ./config.zip
      unzip -o config.zip -d .
      TOKEN=$(jq --raw-output .token token.json)
      printf "Authorization: Bearer %s" $TOKEN > header.txt
      MUUK_USERID_TOKEN=$(jq --raw-output .userId token.json)
      printf '{"property": "%s", "value": ["%s"], "platform": "pw", "userId": "%s"}' $MUUK_PROPERTY $MUUK_HASHTAGH $MUUK_USERID_TOKEN > body.json
      curl -X POST https://portal.muuktest.com:8081/download_byproperty -H @header.txt -d @body.json -H "Content-Type: application/json" -o ./test.zip
      unzip -o test.zip -d ./test
      npm install -D @playwright/test
      npm install axios
      npm initall archiver
      npx playwright test --project=chromium
    displayName: 'Clone and run executor'
    env:
      MUUKTEST_KEY: $(MuuktestKey)
      MUUK_PROPERTY: $(MuuktestProperty)
      MUUK_HASHTAGH: $(MuuktestHashtag)
