
trigger:
- master

pool:
  vmImage: ubuntu-latest
  
container: muuk/muuktest_v1:0.1

environment:
  GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
  GRADLE_USER_HOME: .gradle-home
  
  
steps:
  - checkout
  - run:
      command: |
        Xvfb :99 -screen 0 1366x768x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
        export DISPLAY=:99
        git clone https://github.com/muuklabs/executor.git
        cd executor/
        git checkout success-criteria
        printf '4jyis7x8sjjtn1evnckkm-kbsu65pxboqt2684pig0yc-5mg10jllousjlj2631l93-nsb8askfsreep5gqgb013s' > key.pub
        cat key.pub
        chmod 755 gradlew
        chmod 755 key.pub
        sed -i 's/79.0.3945.36/86.0.4240.22/g' build.gradle
        cat build.gradle
        python3.7 mkcli.py -p hashtag -t uno -browser chrome


