
trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04'
  
container: muuk/muuktest_v1:0.1

steps:

  - script: |
      export GRADLE_OPTS="-Xmx1024m -XX:MaxMetaspaceSize=256m"
      export GRADLE_USER_HOME=".gradle-home"
    displayName: 'Set environment variables'

  - script: |
      Xvfb :99 -screen 0 1366x768x16 &
      export DISPLAY=:99
      ps -ef | grep Xvfb
      git clone https://github.com/muuklabs/executor.git
      cd executor/
      git checkout master
      printf $MUUKTEST_KEY > key.pub
      cat key.pub
      chmod 755 gradlew
      chmod 755 key.pub
      sed -i 's/79.0.3945.36/106.0.5249.61/g' build.gradle
      sed -i 's/0.23.0/0.31.0/g' build.gradle
      cat build.gradle
      python3.8 mkcli.py -p tag -t TC20516 -browser chrome
    displayName: 'Clone and run executor'
    env:
      MUUKTEST_KEY: $(MuuktestKey)
