
trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04'
  
container: muuk/muuktest_v1:0.1

steps:

  - script: |
      export GRADLE_OPTS="-Xmx1024m -XX:MaxMetaspaceSize=256m"
      export GRADLE_USER_HOME=".gradle-home"
    displayName: 'Set environment variables'

  - script: |
      Xvfb :99 -screen 0 1366x768x16 &
      export DISPLAY=:99
      ps -ef | grep Xvfb
      git clone https://github.com/muuklabs/executor.git
      cd executor/
      git checkout videoEnabled
      printf $MUUKTEST_KEY > key.pub
      cat key.pub
      chmod 755 gradlew
      chmod 755 key.pub
      sed -i 's/79.0.3945.36/86.0.4240.22/g' build.gradle
      cat build.gradle
      python3.7 mkcli.py -p hashtag -t $MUUK_HASHTAGH -browser chrome
    displayName: 'Clone and run executor'
    env:
      MUUKTEST_KEY: $(MuuktestKey)
      MUUK_HASHTAGH: $(MuukHashtag)
