
trigger:
- master

pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright:v1.40.0-jammy

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- script: |
    mkdir -p executor
    cd executor
    apt-get update
    apt-get install -y jq
    apt-get install -y unzip
    node -v
    printf '{ "key": "%s"}' $MUUKTEST_KEY > file.json
    curl -H  "Content-Type: application/json" -X POST -d @file.json 'https://portal.muuktest.com:8081/generate_token_executer' -o "token.json"
    curl -X POST https://portal.muuktest.com:8081/api/v1/downloadpwfiles -k -d @file.json -H "Content-Type: application/json" -o ./config.zip
    unzip -o config.zip -d .
    TOKEN=$(jq --raw-output .token token.json)
    printf "Authorization: Bearer %s" $TOKEN > header.txt
    MUUK_USERID_TOKEN=$(jq --raw-output .userId token.json)
    printf '{"property": "%s", "value": ["%s"], "platform": "pw", "userId": "%s"}' $MUUK_PROPERTY $MUUK_HASHTAGH $MUUK_USERID_TOKEN > body.json
    curl -X POST https://portal.muuktest.com:8081/download_byproperty -H @header.txt -d @body.json -H "Content-Type: application/json" -o ./test.zip
    [ -d "./test" ] && rm -r test
    unzip -o test.zip -d ./test
    npm install -D @playwright/test
    npm install axios
    npm install archiver
    npm install cheerio
    npm install xpath
    npm install @xmldom/xmldom
    npm install @faker-js/faker
    npx playwright test --project=chromium
  displayName: 'Execute MuukTest E2E'
  env:
    MUUKTEST_KEY: $(MuuktestKey)
    MUUK_PROPERTY: $(MuuktestProperty)
    MUUK_HASHTAGH: $(MuuktestValue)
    CI: 'true'
